### ISSUE TITLE
The hyper-parameter of IMDB and RACE

### ISSUE THREAD

**Issue by YeDeming** [IBM/PoWER-BERT#6]
HI Saurabh,

I want to reproduce your results in IMDB and RACE. Could you please share the LAMBDA and LR_SOFT_EXTRACT for the IMDB and RACE dataset?

Best,
Deming

**Comment by saurabhiit2007** [comment]
For IMDB you can try using LR_SOFT_EXTRACT=0.0002 and Lambda=0.0007 and for RACE you can use LR_SOFT_EXTRACT=0.0002 and Lambda=0.0001
